### ISSUE TITLE
IndexError: index -9223372036854775808 is out of bounds for dimension 0 with size 256

### ISSUE THREAD

**Issue by vitacon** [Tencent/DepthCrafter#39]
I am trying to run  DepthCrafter in Anaconda in Windows with 8 GB of VRAM. I created an environment for it, it seems all modules are in place and I fed it with a very short video (about 50 frames).

However, it crashes on `image = self.colormap[image]`. Can somebody explain what went wrong?

```
(depthcrafter) C:\Users\Vita\video\DepthCrafter>python run.py  --video-path 495.mp4 --max-res 512
C:\Users\Vita\Anaconda3\envs\depthcrafter\lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.46it/s]
Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Xformers is not enabled
==> processing video:  495.mp4
==> original video shape:  (20, 1080, 1490, 3)
==> downsampled shape: (20, 384, 512, 3), with stride: 1
==> final processing shape: (20, 384, 512, 3)
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:16<00:00,  3.27s/it]
Traceback (most recent call last):
  File "C:\Users\Vita\video\DepthCrafter\run.py", line 185, in <module>
    Fire(main)
  File "C:\Users\Vita\Anaconda3\envs\depthcrafter\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Vita\Anaconda3\envs\depthcrafter\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Vita\Anaconda3\envs\depthcrafter\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\Vita\video\DepthCrafter\run.py", line 160, in main
    depthcrafter_demo.infer(
  File "C:\Users\Vita\video\DepthCrafter\run.py", line 96, in infer
    vis = vis_sequence_depth(res)
  File "C:\Users\Vita\video\DepthCrafter\depthcrafter\utils.py", line 95, in vis_sequence_depth
    res = visualizer.apply(torch.tensor(depths), v_min=v_min, v_max=v_max).numpy()
  File "C:\Users\Vita\video\DepthCrafter\depthcrafter\utils.py", line 85, in apply
    image = self.colormap[image]
IndexError: index -9223372036854775808 is out of bounds for dimension 0 with size 256
```

**Comment by wbhu** [comment]
It seems NaN is founded in predicted depth, what's your test video? Could you please try to test it on the HF demo to see if it works well

**Comment by vitacon** [comment]
Here is my working environment:

```
# packages in environment at C:\Users\Vita\Anaconda3\envs\depthcrafter:
#
# Name                    Version                   Build  Channel
accelerate                1.1.1                    pypi_0    pypi
aiohappyeyeballs          2.4.3           py310haa95532_0  
aiohttp                   3.10.5          py310h827c3e9_0  
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
archspec                  0.2.3              pyhd3eb1b0_0  
arrow-cpp                 16.1.0               h7cd61ee_0  
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3           py310haa95532_0  
attrs                     24.2.0          py310haa95532_0  
aws-c-auth                0.6.19               h2bbff1b_0  
aws-c-cal                 0.5.20               h2bbff1b_0  
aws-c-common              0.8.5                h2bbff1b_0  
aws-c-compression         0.2.16               h2bbff1b_0  
aws-c-event-stream        0.2.15               hd77b12b_0  
aws-c-http                0.6.25               h2bbff1b_0  
aws-c-io                  0.13.10              h2bbff1b_0  
aws-c-mqtt                0.7.13               h2bbff1b_0  
aws-c-s3                  0.1.51               h2bbff1b_0  
aws-c-sdkutils            0.1.6                h2bbff1b_0  
aws-checksums             0.1.13               h2bbff1b_0  
aws-crt-cpp               0.18.16              hd77b12b_0  
aws-sdk-cpp               1.10.55              hd77b12b_0  
blas                      1.0                         mkl  
boltons                   23.0.0          py310haa95532_0  
boost-cpp                 1.82.0               h59b6b97_2  
bottleneck                1.4.2           py310hc99e966_0  
brotli                    1.0.9                h0e60522_4    conda-forge
brotli-python             1.0.9           py310hd77b12b_8  
bzip2                     1.0.8                h2bbff1b_6  
c-ares                    1.34.3               h2466b09_1    conda-forge
ca-certificates           2024.11.26           haa95532_0  
cccl                      2.3.2                h47f531a_0  
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py310h827c3e9_0  
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6           py310haa95532_0  
conda                     24.11.0         py310haa95532_0  
conda-libmamba-solver     24.9.0             pyhd3eb1b0_0  
conda-package-handling    2.4.0           py310haa95532_0  
conda-package-streaming   0.11.0          py310haa95532_0  
contourpy                 1.3.1           py310hc19bc0b_0    conda-forge
cuda-cccl                 12.4.127             haa95532_2  
cuda-cccl_win-64          12.4.127             haa95532_2  
cuda-cudart               12.4.127             hd77b12b_0  
cuda-cudart-dev           12.4.127             hd77b12b_0  
cuda-cudart-dev_win-64    12.4.127             hd77b12b_0  
cuda-cudart-static        12.4.127             hd77b12b_0  
cuda-cudart-static_win-64 12.4.127             hd77b12b_0  
cuda-cudart_win-64        12.4.127             hd77b12b_0  
cuda-cupti                12.4.127             hd77b12b_1  
cuda-libraries            12.4.1               haa95532_1  
cuda-libraries-dev        12.4.1               haa95532_1  
cuda-nvrtc                12.4.127             hd77b12b_1  
cuda-nvrtc-dev            12.4.127             hd77b12b_1  
cuda-nvtx                 12.4.127                      0    nvidia
cuda-opencl               12.4.127             hd77b12b_0  
cuda-opencl-dev           12.4.127             hd77b12b_0  
cuda-profiler-api         12.4.127             haa95532_1  
cuda-runtime              12.4.1               h382c6e5_0  
cuda-version              12.4                 hbda6634_3  
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
datasets                  2.19.1          py310haa95532_0  
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
decord                    0.6.0                    pypi_0    pypi
diffusers                 0.29.1             pyhd8ed1ab_0    conda-forge
dill                      0.3.8           py310haa95532_0  
distro                    1.9.0           py310haa95532_0  
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
fire                      0.6.0              pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                h6d14046_1  
fonttools                 4.55.0          py310h38315fa_0    conda-forge
freetype                  2.12.1               ha860e81_0  
frozendict                2.4.2           py310h2bbff1b_0  
frozenlist                1.5.0           py310h827c3e9_0  
fsspec                    2024.3.1        py310haa95532_0  
gflags                    2.2.2                hd77b12b_1  
glib                      2.78.4               hd77b12b_0  
glib-tools                2.78.4               hd77b12b_0  
glog                      0.5.0                hd77b12b_1  
gmpy2                     2.1.2           py310h7f96b67_0  
gst-plugins-base          1.18.5               h9e645db_0  
gstreamer                 1.18.5               hd78058f_0  
huggingface_hub           0.26.2             pyh0610db2_0    conda-forge
icu                       58.2                 ha925a31_3  
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
intel-openmp              2023.1.0         h59b6b97_46320  
ipython                   8.30.0             pyh7428d3b_0    conda-forge
jedi                      0.19.2             pyhff2d567_0    conda-forge
jinja2                    3.1.4           py310haa95532_1  
jpeg                      9e                   h827c3e9_3  
jsonpatch                 1.33            py310haa95532_1  
jsonpointer               2.1                pyhd3eb1b0_0  
khronos-opencl-icd-loader 2024.05.08           h8cc25b3_0  
kiwisolver                1.4.7           py310hc19bc0b_0    conda-forge
lcms2                     2.12                 h83e58a3_0  
lerc                      3.0                  hd77b12b_0  
libabseil                 20240116.2      cxx17_h5da7b33_0  
libarchive                3.7.4                h9243413_0  
libboost                  1.82.0               h3399ecb_2  
libbrotlicommon           1.0.9                h2bbff1b_8  
libbrotlidec              1.0.9                h2bbff1b_8  
libbrotlienc              1.0.9                h2bbff1b_8  
libclang                  12.0.1          default_h81446c8_4    conda-forge
libcublas                 12.4.5.8             hd77b12b_1  
libcublas-dev             12.4.5.8             hd77b12b_1  
libcufft                  11.2.1.3             hd77b12b_1  
libcufft-dev              11.2.1.3             hd77b12b_1  
libcurand                 10.3.5.147           hd77b12b_1  
libcurand-dev             10.3.5.147           hd77b12b_1  
libcurl                   8.9.1                h0416ee5_0  
libcusolver               11.6.1.9             hd77b12b_1  
libcusolver-dev           11.6.1.9             hd77b12b_1  
libcusparse               12.3.1.170           hd77b12b_1  
libcusparse-dev           12.3.1.170           hd77b12b_1  
libdeflate                1.17                 h2bbff1b_1  
libevent                  2.1.12               h56d1f94_1  
libffi                    3.4.4                hd77b12b_1  
libglib                   2.78.4               ha17d25a_0  
libgrpc                   1.62.2               hf25190f_0  
libiconv                  1.16                 h2bbff1b_3  
libmamba                  1.5.8                h99b1521_3  
libmambapy                1.5.8           py310h77c03ed_3  
libnpp                    12.2.5.30            hd77b12b_1  
libnpp-dev                12.2.5.30            hd77b12b_1  
libnvfatbin               12.4.127             h20ee8b7_2  
libnvfatbin-dev           12.4.127             h20ee8b7_2  
libnvjitlink              12.4.127             hd77b12b_1  
libnvjitlink-dev          12.4.127             hd77b12b_1  
libnvjpeg                 12.3.1.117           hd77b12b_1  
libnvjpeg-dev             12.3.1.117           haa95532_1  
libogg                    1.3.5                h2466b09_0    conda-forge
libpng                    1.6.39               h8cc25b3_0  
libprotobuf               4.25.3               hf2fb9eb_0  
libsolv                   0.7.24               h23ce68f_1  
libssh2                   1.11.1               h2addb87_0  
libthrift                 0.15.0               h4364b78_2  
libtiff                   4.5.1                hd77b12b_0  
libuv                     1.48.0               h827c3e9_0  
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.3.2                h3d04722_1  
libxml2                   2.13.5               h24da03e_0  
lz4-c                     1.9.4                h2bbff1b_1  
markupsafe                2.1.3           py310h2bbff1b_0  
matplotlib                3.8.4           py310h5588dad_2    conda-forge
matplotlib-base           3.8.4           py310hadb10a8_2    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mediapy                   1.2.0              pyhd8ed1ab_0    conda-forge
menuinst                  2.2.0           py310h5da7b33_0  
mkl                       2023.1.0         h6b88ed4_46358  
mkl-service               2.4.0           py310h2bbff1b_1  
mkl_fft                   1.3.11          py310h827c3e9_0  
mkl_random                1.2.8           py310hc64d2fc_0  
mpc                       1.1.0                h7edee0f_1  
mpfr                      4.0.2                h62dcd97_1  
mpir                      3.0.0                hec2e145_1  
mpmath                    1.3.0           py310haa95532_0  
multidict                 6.1.0           py310h827c3e9_0  
multiprocess              0.70.15         py310haa95532_0  
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.3             py310haa95532_0  
numexpr                   2.10.1          py310h4cd664f_0  
numpy                     1.26.4          py310h055cbcc_0  
numpy-base                1.26.4          py310h65a83cf_0  
openjpeg                  2.5.2                hae555c5_0  
openssl                   3.4.0                h2466b09_0    conda-forge
orc                       2.0.1                hd8d391b_0  
packaging                 24.2               pyhff2d567_1    conda-forge
pandas                    2.2.3           py310h5da7b33_0  
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                h0ff8eda_1  
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    11.0.0          py310hb5480e2_0  
pip                       24.3.1             pyh8b19718_0    conda-forge
platformdirs              3.10.0          py310haa95532_0  
pluggy                    1.0.0           py310haa95532_1  
ply                       3.11               pyhd8ed1ab_2    conda-forge
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
propcache                 0.2.0           py310h827c3e9_0  
psutil                    6.1.0                    pypi_0    pypi
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyarrow                   16.1.0          py310hc64d2fc_0  
pybind11-abi              5                    hd3eb1b0_0  
pycosat                   0.6.6           py310h2bbff1b_1  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyqt                      5.15.10         py310hd77b12b_0  
pyqt5-sip                 12.13.0         py310h2bbff1b_0  
pysocks                   1.7.1           py310haa95532_0  
python                    3.10.15              h4607a30_1  
python-dateutil           2.9.0post0      py310haa95532_2  
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python-xxhash             2.0.2           py310h2bbff1b_1  
python_abi                3.10                    2_cp310    conda-forge
pytorch                   2.5.1           py3.10_cuda12.4_cudnn9_0    pytorch
pytorch-cuda              12.4                 h3fd98bf_7    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.2             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py310h827c3e9_0  
qt-main                   5.15.2               he8e5bd7_7  
re2                       2022.04.01           hd77b12b_0  
regex                     2024.9.11       py310h827c3e9_0  
reproc                    14.2.4               hd77b12b_2  
reproc-cpp                14.2.4               hd77b12b_2  
requests                  2.32.3          py310haa95532_1  
ruamel.yaml               0.18.6          py310h827c3e9_0  
ruamel.yaml.clib          0.2.8           py310h827c3e9_0  
safetensors               0.4.5           py310haa69e8e_1  
setuptools                75.6.0             pyhff2d567_1    conda-forge
sip                       6.7.12          py310h00ffb61_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.2.1                hcdb6601_0  
sqlite                    3.45.3               h2bbff1b_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sympy                     1.13.1                   pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0  
termcolor                 2.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.14               h0416ee5_0  
tokenizers                0.19.1          py310h7ac788d_0  
tomli                     2.2.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4.2           py310ha8f682b_0    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
transformers              4.41.2             pyhd8ed1ab_0    conda-forge
truststore                0.8.0           py310haa95532_0  
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                h04d1e81_0  
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
unicodedata2              15.1.0          py310ha8f682b_1    conda-forge
urllib3                   2.2.3           py310haa95532_0  
utf8proc                  2.6.1                h2bbff1b_1  
vc                        14.40                h2eaa2aa_1  
vc14_runtime              14.42.34433         he29a5d6_23    conda-forge
vs2015_runtime            14.42.34433         hdffcdeb_23    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.45.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0           py310haa95532_0  
xxhash                    0.8.0                h2bbff1b_3  
xz                        5.4.6                h8cc25b3_1  
yaml                      0.2.5                he774522_0  
yaml-cpp                  0.8.0                hd77b12b_1  
yarl                      1.18.0          py310h827c3e9_0  
zipp                      3.21.0             pyhd8ed1ab_1    conda-forge
zlib                      1.2.13               h8cc25b3_1  
zstandard                 0.23.0          py310h4fc1ca9_1  
zstd                      1.5.6                h8880b57_0  

```

**Comment by wbhu** [comment]
thx for sharing. Closed as completed

**Comment by Zanue** [comment]
I met the same issue and solved it by `pip install xformers`.
